### ISSUE TITLE
log-transformation

### ISSUE THREAD

**Issue by mbuttner** [drisso/archive-RUVSeq#16]
Hi,

I have tried to input TPM-normalised data in RUVg. It appears that unless the input data are counts, only log-transformed data are returned. I will provide an example upon request. However, I would expect RUVg to return corrected data on the same scale as the input data. 

Best regards.

**Comment by drisso** [comment]
Hi @mbuttner 

the RUVSeq package is designed to only handle counts, not TPM, because it assumes a Negative Binomial model, which is specifically for count data. Our suggested workflow is to work with counts, possibly scaled by upper-quartile (see vignette). 

If you really want to work with (log) TPM, you can use the linear-model version of RUV, available on CRAN:
https://cran.r-project.org/web/packages/ruv/index.html
