### ISSUE TITLE
explanation of RUV

### ISSUE THREAD

**Issue by patterja** [drisso/archive-RUVSeq#18]
I am wondering if you could give me an explanation of the results I am getting from RUVs. I understand that this particular application of RUV uses factor analysis to adjust for technical effects from negative control samples by identifying genes or samples that are not affected by the biological covariates of interest but are still affected by the factors of unwanted variation. I am not clear on how factor analysis attributes or corrects for that unwanted variation that it identifies. 
For example, If I had replicates within an RNAseq experiment with expression values that varied drastically across a particular gene, one would assume that this variation is attributed to unwanted variation and factor analysis would attempt to minimize or correct for the variation between these replicates. Could you clarify the logic behind factor analysis with the following observed values in this RNAseq experiment. The counts for a particular gene are the following:

 |  Gene  |  Sample A R1  | Sample A R2 | Sample A R3  | Sample A R4 | Sample B R1   |  Sample B R2  | 
|-----------|-----------|----------|-----------|----------|----------|----------|
| ENSG00000283029.1 | 453    | 0        | 157   | 1456  |   202 | 0 |

When I run RUVs correction over the matrix with these replicates with a k=2. The values for his gene turn into:

|  Gene  |  Sample A R1 | Sample A R2 | Sample A R3| Sample A R4 | Sample B R1  |  Sample B R2  | 
|-----------|-----------|----------|-----------|----------|----------|----------|
|ENSG00000283029.1 |  386441591  |  966143   | 561584542 | 20900044 | 21407 |  44 |

The expression values have essentially been inflated. I'm not sure I understand the logic of inflating these values, it may be to turn the values into an obvious outlier and would work in most data usage cases but would clearly not be applicable to RNAseq analysis. This gene's expression, with its fairly average length, ultimately becomes artificially inflated even when corrected for overall gene length or depth. Would you be able to explain the logic behind this inflation?
Does it make sense to apply depth and gene size normalization after RUVseq? Or does factor analysis essentially inflate or deflate the differences based on correlated variables removing the overall logic of correcting by the total reads and gene length, like converting to TPMs/FPKMs?

**Comment by drisso** [comment]
Hi @patterja ,

I'm not sure why you see these results for this particular gene. The main idea behind any factor analysis model is that the data (in this case the unwanted variation) is an intrinsically low-rank signal, so the noise does not act on each gene independently, but rather in some coordinated way that can be explained by just a few factors.

So, to look at the values of one gene irrespective of the rest of the genes may or may not make sense. 

In the RUVSeq package, we use the RUVs function to estimate some factors of unwanted variation (`W`) that can then be added as additional covariates in a model for differential expression. 

What you are reporting for your particular example, I assume are the "normalized values" that we also return in the RUVs package. Those values should not be used directly for differential expression or for computing TPMs/FPKMs values, but we return them because we have found them useful for visualization and for understanding if the data are well normalized.

I would not recommend looking at the values of any particular gene and giving them too much meaning.

That said, this particular example look odd. Is that gene particular in any way? Are the other genes in a very different scale? Is this one of the genes used as negative controls or not?

Also, it would be nice to see the exact code that you used.

**Comment by patterja** [comment]
Thanks for the quick response. To answer your questions above:

`Is that gene particular in any way?`
Not that I know of and it's function does not suggest it should be especially differentiated or overexpressed to this degree. I would assume based on the complete variability between all the replicates R1-R4 in Sample A and Sample B R1-R3, it is in fact a major source of unwanted variation. 

` Are the other genes in a very different scale?`
The counts are mostly around the median. But the normalized values are the values that are now in the upper quartile if not the maximum expression value and the only thing I can contribute this to is the inconsistency across the replicates. 

`Is this one of the genes used as negative controls or not?`
 Based on the documentation I used all the genes to estimate unwanted factors, W, because as the documentation mentions that "RUVs, ... performs well even when its step 4 is based on all genes ...". 

You say that the "normalized values" from RUVs should not be used for differential expression or conversion to TPM. I understand, that counts data is needed for differential expression analysis. If I wanted to see the effects of RUV4 with the applied W as a covariate in a regression model isn't this what the normalizedCounts essentially contains or is it necessary to apply the GLM with the W values to get correctly adjusted RUV fitted values? I understand that there might be chance of removing factors that may be of biological significance but what is the distinction of running GLM with the W versus the contents of normalizedCounts(ruv_set)?

A simplified version of the code I am running for RUVs is simply with `mat` being matrix of expression counts with gene names as rows and samples in columns. 
```
eset = newSeqExpressionSet(as.matrix(mat))
ruvs_set = RUVs(eset, cIdx=allgenesfiltered, k=1, scIdx=newreps)
```
Where newreps consists of a matrix with one row and 7 columns
```
> newreps
       [,1] [,2] [,3] [,4]
 [1,]   1   2   3   4
 [2,]   5   6   7   -1
```
The tables in the last post consisted of the counts and normalizedCounts from the ruv_set matrix.
The GLM was fit with edgeR.
```
sampID=c("SampleA","SampleA","SampleA","SampleA","SampleB","SampleB","SampleB")
design <- model.matrix(~sampID + W_1, data=pData(ruvs_set))
y <- DGEList(counts=counts(ruvs_set), group=sampID)
y <- calcNormFactors(y, method="upperquartile")
y <- estimateGLMCommonDisp(y, design)
y <- estimateGLMTagwiseDisp(y, design)
fit <- glmFit(y, design)
```
ENSG00000283029.1 with GLM.

 |  Gene  |  Sample A R1  | Sample A R2 | Sample A R3  | Sample A R4 | Sample B R1   |  Sample B R2  | 
|-----------|-----------|----------|-----------|----------|----------|----------|
| ENSG00000283029.1 | 1535.851    | 964.0926   | 1527.734   | 515.5279  |   101.0003 | 117 |

**Comment by drisso** [comment]
So it looks like the GLM fit for that particular gene is fine, and that's what matters in my opinion.

The `normalizedCounts` slot contains the simple rescaled residuals from just removing `W alpha` from the log-counts, so it's not something that you would want to use for downstream analyses, but rather something that we find useful as a exploratory tool to see if the normalization "worked".

I guess I'm still surprised that the fitted values from the GLM are that different from the residuals of the linear model, but it may just be a particularly pathological situation.

One more thing: our recommended pipeline is to start with a global scaling step before applying RUV. If you don't do that your inferred W will essentially capture the difference in sequencing depth, mimicking the effect of the normalization factors estimated by `calcNormFactors`.

**Comment by patterja** [comment]
Thanks for the input. 
I am also surprised by the differences in the GLM versus the normalizedCounts slot for exploration. The PCA is markedly different as well, with sample replicates that were tightly clustering with the simple rescaled residuals but don't cluster with PC1, PC2 or PC3 in the weighted GLM. 

In github issue #16 log-transformation, you mention that the RUVseq assumes a negative binomial distrubution, would a global scaling step prior to applying RUV maintain this negative binomial distribution? 
If the negative binomial model holds true for any scaled counts, for example, counts adjusted to TPMs, couldn't RUVseq be applied to TPM as well? I guess this is becoming a question about edgeR and how to adjust for gene length with normalized counts based on a GLM.  But I do think it's crucial component to correct for when trying to interpret expression values by themselves,  given RNAseq's bias for longer transcripts.

**Comment by drisso** [comment]
So there are two different steps to a typical RUVSeq analysis:

1. Estimate the factors of unwanted variation. For this, we take the log of the counts, scale them by upper-quartile or similar global normalization, estimate the factors by linear factor analysis. This is obviously an approximation that doesn't involve the negative binomial.
2. Plug-in the estimated factors in a negative binomial model to estimate all the other parameters (with focus on the differential expression coefficients). This is where having the raw counts is important and hence you include the scaling factors as offsets.

Note that if your focus is differential expression, you can include gene-specific offsets that account for more than a single global-scaling parameter. We and others have done some work to include offsets for GC-content correction (which may be important for DE). We never found it useful to include an offset to account for gene-length, because we found that length effects are not sample specific and hence cancel out when looking at DE.

IMO, no matter how many biases you account for, there is no hope with current RNA-seq technologies to get an absolute expression estimate, and reasoning in relative terms is more useful. E.g., which genes are highly expressed in one condition compared to another.

Gene length becomes important if you compare across genes, of course. But in that case you have to be careful, because the right unit is probably isoform (and isoform length) rather than gene. Looking at TPMs estimated by RSEM or similar may be more useful. And perhaps even considering a proper variance-stabilizing transformation instead of the log (see the `vst()` function in `DESeq2`).
